//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoryClient.Cross.Core.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MemoryClient.Cross.Core.Localization.Locale", typeof(Locale).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try logging in again..
        /// </summary>
        internal static string LoadingScreen_ExceptionText {
            get {
                return ResourceManager.GetString("LoadingScreen.ExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while authenticating.
        /// </summary>
        internal static string LoadingScreen_ExceptionTitle {
            get {
                return ResourceManager.GetString("LoadingScreen.ExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email/Username:.
        /// </summary>
        internal static string LoginDialog_IdentifierLabel {
            get {
                return ResourceManager.GetString("LoginDialog.IdentifierLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginDialog_LoginButton {
            get {
                return ResourceManager.GetString("LoginDialog.LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string LoginDialog_PasswordLabel {
            get {
                return ResourceManager.GetString("LoginDialog.PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account? Register.
        /// </summary>
        internal static string LoginDialog_RegisterLink {
            get {
                return ResourceManager.GetString("LoginDialog.RegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay logged in?.
        /// </summary>
        internal static string LoginDialog_StayLoggedInLabel {
            get {
                return ResourceManager.GetString("LoginDialog.StayLoggedInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginDialog_Title {
            get {
                return ResourceManager.GetString("LoginDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string RegisterDialog_Cancel {
            get {
                return ResourceManager.GetString("RegisterDialog.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string RegisterDialog_EmailLabel {
            get {
                return ResourceManager.GetString("RegisterDialog.EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password:.
        /// </summary>
        internal static string RegisterDialog_PasswordAgainLabel {
            get {
                return ResourceManager.GetString("RegisterDialog.PasswordAgainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string RegisterDialog_PasswordLabel {
            get {
                return ResourceManager.GetString("RegisterDialog.PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just one step left! Enter a username and password for the site below. You can use the password or {0} to sign in in the future..
        /// </summary>
        internal static string RegisterDialog_ProviderText {
            get {
                return ResourceManager.GetString("RegisterDialog.ProviderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterDialog_RegisterButton {
            get {
                return ResourceManager.GetString("RegisterDialog.RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterDialog_Title {
            get {
                return ResourceManager.GetString("RegisterDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string RegisterDialog_UsernameLabel {
            get {
                return ResourceManager.GetString("RegisterDialog.UsernameLabel", resourceCulture);
            }
        }
    }
}
